export const words = {
  ru: {
    visitorNnativeLanguage: "Родной язык посетителя - ",
    portion: "порция",
    cost: "стоимость",
    pieces: "штуки",

    totalCost: "Стоимость блюд в корзине: <br>",
    yourOrderTitle: "Ваш заказ",
    sendOrder: "Отправить заказ",
    updateOrder: "Добавить к заказу",

    yourCart: "Корзина:",
    announcement: "",
    announcementText: "Выберите желаемые блюда, затем пригласите официанта и покажите ему корзину.",
    googleFedback: "Оставьте отзыв",
    deletePortionMessage: "Удалить порцию?",

    textSendOrder: "Заказ успешно отправлен!",
    textErrorSendOrder: "Ошибка при отправке заказа. Пожалуйста, попробуйте ещё раз или пригласите официанта.",
    textAskTableNumber: "Пожалуйста, введите номер стола. Его можно увидеть на QR-коде, который находится на вашем столе.",
    totalCostOrder: "Стоимость заказа: ",
    yourOrderButton: "Ваш заказ<br>№",
    payOrderButton: "Оплатить",

    tableNumber: "🍽️ Стол № ",
    orderNumber: "#️⃣ Номер заказа",
    newOrderMessage: "‼️🔴 Новый заказ!\n",
    updateOrderMessage: "‼️🟢 Обновление заказа\n",
    oldDishes: "🟨 Прошлые блюда:",
    newDishes: "🟩 Новые блюда:",
    listDishes: "📃 Список блюд:",

    IQRMenuLink: "Заказать меню",
    selectPaymentMethod: "Выберете способ оплаты",
    cash: "Наличные",
    bankCard: "Карта",
    cancelButton: "Отмена",
    waiterWillCome: "Спасибо! Скоро к вам придет официант.",
    errorInviteWaiter: "Что-то пошло не так, пожалуйста пригласите официанта",
    enterCorrectly: "Пожалуйста введите корректно номер стола",
    textMessage: "💵 Оплата заказа!\n\n#️⃣ Номер закза -\n${orderId}\n🍽️ Стол № ${tableNumber}\n💶💳 Способ оплаты - ${paymentMethod}\n\n📃 Вот чек:\n ${orderListText}\n💰 Итого: ${totalCostMessage} ${currencySymbol}\n",


  },
  en: {
    visitorNnativeLanguage: "Visitor's native language - ",
    portion: "portion",
    cost: "cost",
    pieces: "pieces",

    totalCost: "Total cost of dishes in the cart: <br>",
    yourOrderTitle: "Your order",
    sendOrder: "Send order",
    updateOrder: "Add to order",

    yourCart: "Cart:",
    announcement: "",
    announcementText: "Select the desired dishes, then call the waiter and show them the cart.",
    googleFedback: "Leave feedback",
    deletePortionMessage: "Delete portion?",

    textSendOrder: "Order sent successfully!",
    textErrorSendOrder: "Error sending order. Please try again or call the waiter.",
    textAskTableNumber: "Please enter your table number. You can find it on the QR code located on your table.",
    totalCostOrder: "Order cost: ",
    yourOrderButton: "Your order<br>№",

    tableNumber: "🍽️Table № ",
    orderNumber: "#️⃣ Order number",
    newOrderMessage: "‼️🔴 New order!\n",
    updateOrderMessage: "‼️🟢 Order update\n",
    oldDishes: "🟨 Previous dishes:",
    newDishes: "🟩 New dishes:",
    listDishes: "📃 List of dishes:",
    payOrderButton: "Pay",

    IQRMenuLink: "Order menu",
    selectPaymentMethod: "Choose a payment method",
    cash: "Cash",
    bankCard: "Card",
    cancelButton: "Cancel",
    waiterWillCome: "Thank you! A waiter will come to you soon.",
    errorInviteWaiter: "Something went wrong, please call a waiter.",
    enterCorrectly: "Please enter the table number correctly.",
    textMessage: "💵 Order payment!\n\n#️⃣ Order number -\n${orderId}\n🍽️ Table № ${tableNumber}\n💶💳 Payment method - ${paymentMethod}\n\n📃 Here is the receipt:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n"
  },
  es: {
    visitorNnativeLanguage: "Idioma nativo del visitante - ",
    portion: "porción",
    cost: "costo",
    pieces: "piezas",

    totalCost: "Costo total de los platos en el carrito: <br>",
    yourOrderTitle: "Tu pedido",
    sendOrder: "Enviar pedido",
    updateOrder: "Agregar al pedido",

    yourCart: "Carrito:",
    announcement: "",
    announcementText: "Selecciona los platos deseados, luego llama al mesero y muéstrale el carrito.",
    googleFedback: "Deja tu opinión",
    deletePortionMessage: "¿Eliminar porción?",

    textSendOrder: "¡Pedido enviado con éxito!",
    textErrorSendOrder: "Error al enviar el pedido. Por favor, inténtalo de nuevo o llama al mesero.",
    textAskTableNumber: "Por favor, ingresa el número de tu mesa. Puedes encontrarlo en el código QR ubicado en tu mesa.",
    totalCostOrder: "Costo del pedido: ",
    yourOrderButton: "Tu pedido<br>№",

    tableNumber: "🍽️ Mesa № ",
    orderNumber: "#️⃣ Número de pedido",
    newOrderMessage: "‼️🔴 ¡Nuevo pedido!\n",
    updateOrderMessage: "‼️🟢 Actualización del pedido\n",
    oldDishes: "🟨 Platos anteriores:",
    newDishes: "🟩 Platos nuevos:",
    listDishes: "📃 Lista de platos:",
    payOrderButton: "Pagar",

    IQRMenuLink: "Pedir menú",
    selectPaymentMethod: "Elige un método de pago",
    cash: "Efectivo",
    bankCard: "Tarjeta",
    cancelButton: "Cancelar",
    waiterWillCome: "¡Gracias! Un mesero vendrá pronto.",
    errorInviteWaiter: "Algo salió mal, por favor llama a un mesero.",
    enterCorrectly: "Por favor, ingresa correctamente el número de mesa.",
    textMessage: "💵 ¡Pago del pedido!\n\n#️⃣ Número de pedido -\n${orderId}\n🍽️ Mesa Nº ${tableNumber}\n💶💳 Método de pago - ${paymentMethod}\n\n📃 Aquí está el recibo:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n"
  },
  pt: {
    visitorNnativeLanguage: "Idioma nativo do visitante - ",
    portion: "porção",
    cost: "custo",
    pieces: "peças",

    totalCost: "Custo total dos pratos no carrinho: <br>",
    yourOrderTitle: "Seu pedido",
    sendOrder: "Enviar pedido",
    updateOrder: "Adicionar ao pedido",

    yourCart: "Carrinho:",
    announcement: "",
    announcementText: "Selecione os pratos desejados, depois chame o garçom e mostre o carrinho.",
    googleFedback: "Deixe sua opinião",
    deletePortionMessage: "Remover porção?",

    textSendOrder: "Pedido enviado com sucesso!",
    textErrorSendOrder: "Erro ao enviar o pedido. Por favor, tente novamente ou chame o garçom.",
    textAskTableNumber: "Por favor, insira o número da sua mesa. Você pode encontrá-lo no código QR localizado na sua mesa.",
    totalCostOrder: "Custo do pedido: ",
    yourOrderButton: "Seu pedido<br>№",
    payOrderButton: "Pagar",

    tableNumber: "🍽️ Mesa № ",
    orderNumber: "#️⃣ Número do pedido",
    newOrderMessage: "‼️🔴 Novo pedido!\n",
    updateOrderMessage: "‼️🟢 Atualização do pedido\n",
    oldDishes: "🟨 Pratos anteriores:",
    newDishes: "🟩 Pratos novos:",
    listDishes: "📃 Lista de pratos:",

    IQRMenuLink: "Pedir cardápio",
    selectPaymentMethod: "Escolha um método de pagamento",
    cash: "Dinheiro",
    bankCard: "Cartão",
    cancelButton: "Cancelar",
    waiterWillCome: "Obrigado! Um garçom virá até você em breve.",
    errorInviteWaiter: "Algo deu errado, por favor, chame um garçom.",
    enterCorrectly: "Por favor, insira o número da mesa corretamente.",
    textMessage: "💵 Pagamento do pedido!\n\n#️⃣ Número do pedido -\n${orderId}\n🍽️ Mesa nº ${tableNumber}\n💶💳 Método de pagamento - ${paymentMethod}\n\n📃 Aqui está o recibo:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n"
  }
}